# Generated by Django 4.1.7 on 2023-05-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0004_alter_demandeprojet_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(default=None, max_length=250, null=True, upload_to='media/')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.projet')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.service')),
            ],
        ),
    ]
